export enum Actions {
    INIT = "INIT",
    START_GAME = "START_GAME",
    PLACE_BET = "PLACE_BET",
    SPIN_START = "SPIN_START",
    RESULT_LOADED = "RESULT_LOADED",
    BETS_OPEN = "BETS_OPEN",
    GAME_OVER = "GAME_OVER",
}