export enum Actions {
    SHOW_SCENE = "SHOW_SCENE",
    HIDE_SCENE = "HIDE_SCENE",
    SPIN_START = "SPIN_START",
    RESULT_LOADED = "RESULT_LOADED",
    SPIN_STOP = "SPIN_STOP",
    START_GAME = "START_GAME",
}