export enum Texts {
    START_TITLE = "START_TITLE",
    START_BUTTON = "START_BUTTON",

    GAME_OVER_TITLE = "GAME_OVER_TITLE",
    GAME_OVER_TEXT = "GAME_OVER_TEXT",
    GAME_OVER_BUTTON = "GAME_OVER_BUTTON",

    BALANCE = "BALANCE",
    BET_BUTTON = "BET_BUTTON",
    SPIN_BUTTON = "SPIN_BUTTON",
}